### ISSUE TITLE
Less than 6 characters

### ISSUE THREAD

**Issue by ElizabethKlein** [Phi--Phi/PasswordGen#2]
When the number of characters is 6, and I click on the minus button, the program freezes for a couple seconds.

This is release v0.1-alpha
I am using java 10.0.2
My laptop is using Windows 10.  My CPU is an Intel(R) Core(TM) i7-4810MQ CPU @ 2.8GHz. My ram is an 8.0 GB DDR3.

**Comment by Phi--Phi** [comment]
Duplicate Issue, refer to #1
